# Generated by Django 5.1.15 on 2026-07-09 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('method', models.CharField(choices=[('gateway', 'Gateway'), ('manual', 'Manual')], max_length=10)),
                ('amount', models.IntegerField(help_text='Locked from the variant discount price or custom plan price at payment time.')),
                ('period_start', models.DateField(blank=True, help_text='Coverage start; set when the payment succeeds.', null=True)),
                ('period_end', models.DateField(blank=True, help_text='period_start + the variant/custom plan duration.', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Gateway txn id; null for manual.', max_length=255, null=True, unique=True)),
                ('company', models.ForeignKey(blank=True, help_text='Nulled on company delete — the financial record survives.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('open_site_limit', models.IntegerField(help_text='Snapshot; -1 means no limit.')),
                ('active_user_limit', models.IntegerField()),
                ('active_labour_limit', models.IntegerField()),
                ('paid_until', models.DateField(blank=True, help_text='From the succeeding payment; null = never activated. Free is an ordinary plan tier.', null=True)),
                ('company', models.OneToOneField(help_text='One row per company — the current entitlement cache, updated in place.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
