# Generated by Django 5.1.15 on 2026-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='active_labour_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active_user_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='open_site_limit',
            field=models.IntegerField(default=0, help_text='Snapshot; -1 means no limit.'),
        ),
    ]
