# Generated by Django 5.1.15 on 2026-09-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_active_labour_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='open_site_limit',
            new_name='site_limit',
        ),
    ]
