# Generated by Django 5.1.15 on 2026-09-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_open_site_limit_site_limit'),
        ('company', '0003_company_active_labour_limit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
