# Generated by Django 5.1.15 on 2026-07-07 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='sites.site'),
        ),
        migrations.AddField(
            model_name='usersite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='uq_user_name_company'),
        ),
        migrations.AddConstraint(
            model_name='usersite',
            constraint=models.UniqueConstraint(fields=('user', 'site'), name='uq_usersite_user_site'),
        ),
    ]
