# Generated by Django 5.1.15 on 2026-07-09 08:23

from django.db import migrations


def create_default_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    groups = [
        "Company Admin",
        "Site Manager",
        "Site Auditor",
    ]

    for group_name in groups:
        Group.objects.get_or_create(name=group_name)


def delete_default_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.filter(
        name__in=[
            "Company Admin",
            "Site Manager",
            "Site Auditor",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_default_groups,
            reverse_code=delete_default_groups,
        ),
    ]