# Generated by Django 5.1.15 on 2026-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_companyadmin',
            field=models.BooleanField(default=False, help_text='Company owner/admin; bypasses site assignment checks.'),
        ),
    ]
