# Generated by Django 5.1.15 on 2026-08-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_companyadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersite',
            name='created_by',
        ),
    ]
