# Generated by Django 5.1.15 on 2026-08-24 15:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_photo_upload_to),
        ),
    ]
