# Generated by Django 5.1.15 on 2026-09-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_photo'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('platform', 'Platform'), ('tenant_system', 'Tenant system'), ('tenant', 'Tenant')], default='tenant', help_text='platform: system group for platform users. tenant_system: system group for tenant users; register/seed only. tenant: assignable via the tenant user API.', max_length=32)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
        ),
    ]
