# Generated by Django 5.1.15 on 2026-08-03 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_companyconfig'),
        ('sites', '0005_remove_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(help_text='Snapshot of actor display name at action time.', max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=16)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('site', 'Site'), ('billing_category', 'Billing category'), ('site_cash', 'Site cash'), ('private_site_cash', 'Private site cash'), ('labour', 'Labour'), ('labour_payment', 'Labour payment'), ('attendance', 'Attendance'), ('labour_session', 'Labour session')], max_length=32)),
                ('entity_id', models.BigIntegerField(help_text='PK of the business row at action time (may no longer exist).')),
                ('business_date', models.DateField(blank=True, help_text="Record's business date when applicable (e.g. attendance.date).", null=True)),
                ('summary', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, help_text='Create: key-field snapshot. Update: {field: {old, new}}. Delete: last snapshot.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, help_text='Optional note when an auditor marks this log reviewed.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the action was performed (audit clock).')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, help_text='Denormalized site scope when the entity is site-related.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='actlog_company_created_idx'), models.Index(fields=['site', '-created_at'], name='actlog_site_created_idx'), models.Index(fields=['entity_type', 'entity_id'], name='actlog_entity_idx'), models.Index(fields=['company', 'reviewed_at'], name='actlog_company_reviewed_idx'), models.Index(fields=['actor', '-created_at'], name='actlog_actor_created_idx')],
            },
        ),
    ]
