# Generated by Django 5.1.15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0002_companyconfig"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("sites", "0004_privatesitecash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "action_flag",
                    models.CharField(
                        choices=[
                            ("addition", "Addition"),
                            ("change", "Change"),
                            ("deletion", "Deletion"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        help_text='Per-field diff: {"field": {"before": ..., "after": ...}}'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="company.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["company", "site", "-created_at"],
                        name="activity_ac_company_26a95b_idx",
                    ),
                    models.Index(
                        fields=["site", "-created_at"],
                        name="activity_ac_site_id_1b92d7_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="activity_ac_content_ee8889_idx",
                    ),
                    models.Index(
                        fields=["actor"],
                        name="activity_ac_actor_i_29e3da_idx",
                    ),
                ],
            },
        ),
    ]
