# Generated by Django 5.1.15 on 2026-08-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='summary',
        ),
    ]
