# Generated by Django 5.1.15 on 2026-08-03 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_summary'),
        ('company', '0002_companyconfig'),
        ('labours', '0011_remove_created_by'),
        ('sites', '0005_remove_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='labour',
            field=models.ForeignKey(blank=True, help_text='Denormalized labour when the entity is labour-related.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='labours.labour'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='labour_name',
            field=models.CharField(blank=True, help_text='Snapshot of labour name at action time (for client messages).', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['labour', '-created_at'], name='actlog_labour_created_idx'),
        ),
    ]
