# Generated by Django 5.1.15 on 2026-08-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_add_labour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(choices=[('user', 'User'), ('site', 'Site'), ('billing_category', 'Billing category'), ('site_cash', 'Site cash'), ('private_site_cash', 'Private site cash'), ('labour', 'Labour'), ('daily_record', 'Daily record'), ('labour_session', 'Labour session')], max_length=32),
        ),
    ]
