# Generated by Django 5.1.15 on 2026-07-12 04:18

import company.models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_transfer_allowed', models.BooleanField(default=True)),
                ('attendance_present_choices', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=3), default=company.models.default_present_choices, help_text='Allowed present values per attendance row.', size=None)),
                ('salary_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_max', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(0)])),
                ('fooding_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fooding_max', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)])),
                ('advance_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('advance_max', models.IntegerField(default=100000, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='company.company')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('salary_min__gte', 0), ('salary_max__gte', models.F('salary_min'))), name='chk_siteconfig_salary_range'), models.CheckConstraint(condition=models.Q(('fooding_min__gte', 0), ('fooding_max__gte', models.F('fooding_min'))), name='chk_siteconfig_fooding_range'), models.CheckConstraint(condition=models.Q(('advance_min__gte', 0), ('advance_max__gte', models.F('advance_min'))), name='chk_siteconfig_advance_range')],
            },
        ),
    ]
