# Generated by Django 5.1.15 on 2026-08-07 06:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_companyconfig'),
        ('sites', '0006_remove_sitecash_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('default_attendance', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('default_salary', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_fooding', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_session_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('current_site', models.ForeignKey(blank=True, help_text='One site at a time; reassign = move. NULL = unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labours', to='sites.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('present', models.DecimalField(blank=True, choices=[(Decimal('0'), '0'), (Decimal('0.5'), '0.5'), (Decimal('1'), '1'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3')], decimal_places=2, max_digits=12, null=True)),
                ('wage', models.IntegerField(blank=True, help_text='Snapshot from labour.default_salary.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('extra_earn', models.IntegerField(blank=True, help_text='Extra work amount for the day.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fooding_pay', models.IntegerField(blank=True, help_text='Fooding cash paid this day.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('advance_pay', models.IntegerField(blank=True, help_text='Advance cash paid this day.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('return_amount', models.IntegerField(blank=True, help_text='Cash returned by labour this day.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sealed', models.BooleanField(default=False, help_text='True = immutable; set by work-session seal.')),
                ('billing', models.ForeignKey(blank=True, help_text='Optional billing category; site may run without categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_records', to='sites.billingcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_records', to='sites.site')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_records', to='labours.labour')),
            ],
        ),
        migrations.CreateModel(
            name='LabourSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='First record date after the previous session ended.')),
                ('end_date', models.DateField(help_text='Last sealed record date.')),
                ('created_date', models.DateField(default=django.utils.timezone.localdate)),
                ('present_days', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('salary_earnings', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('extra_earnings', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_fooding_pay', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_advance_pay', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_return', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('affected_rows', models.PositiveIntegerField(help_text='DailyRecord rows sealed into this session.')),
                ('previous_payable', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='labours.labour')),
            ],
        ),
        migrations.AddConstraint(
            model_name='labour',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_labour_company_name'),
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('date', 'labour'), name='uq_daily_record_date_labour'),
        ),
        migrations.AddConstraint(
            model_name='laboursession',
            constraint=models.UniqueConstraint(fields=('created_date', 'labour'), name='uq_labour_session_created_date_labour'),
        ),
    ]
