# Generated by Django 5.1.15 on 2026-07-16 17:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyconfig'),
        ('labours', '0001_initial'),
        ('sites', '0002_billingcategory_site_is_closed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('return', 'Return')], default='payment', help_text='Payment or Return', max_length=16)),
                ('category', models.CharField(blank=True, choices=[('advance', 'Advance'), ('fooding', 'Fooding')], help_text='Must be empty for returns.', max_length=16, null=True)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sealed', models.BooleanField(default=False, help_text='True = immutable')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='labours.labour')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='labour_payments', to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'labour', 'type'), name='uq_labour_payment_date_labour_type')],
            },
        ),
    ]
