# Generated by Django 5.1.15 on 2026-08-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyconfig'),
        ('labours', '0001_initial_daily_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='laboursession',
            name='uq_labour_session_created_date_labour',
        ),
        migrations.RemoveField(
            model_name='laboursession',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='labour',
            name='last_session_date',
            field=models.DateField(blank=True, help_text='Cached latest labour session end_date; new records must be after this.', null=True),
        ),
        migrations.AddConstraint(
            model_name='laboursession',
            constraint=models.UniqueConstraint(fields=('labour', 'start_date'), name='uq_labour_session_labour_start_date'),
        ),
        migrations.AddConstraint(
            model_name='laboursession',
            constraint=models.UniqueConstraint(fields=('labour', 'end_date'), name='uq_labour_session_labour_end_date'),
        ),
    ]
