# Generated by Django 5.1.15 on 2026-07-17 08:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyconfig'),
        ('labours', '0002_labourpayment'),
        ('sites', '0002_billingcategory_site_is_closed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('present', models.DecimalField(blank=True, choices=[(Decimal('0'), '0'), (Decimal('0.5'), '0.5'), (Decimal('1'), '1'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3')], decimal_places=2, max_digits=12, null=True)),
                ('salary', models.IntegerField(blank=True, help_text='Snapshot from labour.default_salary.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('extra', models.IntegerField(blank=True, help_text='Extra work amount for the day.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sealed', models.BooleanField(default=False, help_text='True = immutable; set by work-session seal.')),
                ('billing', models.ForeignKey(blank=True, help_text='Optional billing category; site may run without categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='sites.billingcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendances', to='labours.labour')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendances', to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'labour'), name='uq_attendance_date_labour')],
            },
        ),
    ]
