# Generated by Django 5.1.15 on 2026-08-24 15:28

import labours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0002_remove_laboursession_uq_labour_session_created_date_labour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=labours.models.labour_photo_upload_to),
        ),
    ]
