# Generated by Django 5.1.15 on 2026-07-15 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyconfig'),
        ('labours', '0002_labourpayment_labourreturn'),
        ('sites', '0002_billingcategory_site_is_closed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labourpayment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='labourreturn',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='labourpayment',
            name='site_total',
            field=models.BigIntegerField(help_text='Per-site running total across all payment types.'),
        ),
        migrations.AddConstraint(
            model_name='labourpayment',
            constraint=models.UniqueConstraint(fields=('labour', 'date'), name='uq_labour_payment_labour_date'),
        ),
        migrations.AddConstraint(
            model_name='labourreturn',
            constraint=models.UniqueConstraint(fields=('labour', 'date'), name='uq_labour_return_labour_date'),
        ),
    ]
