# Generated by Django 5.1.15 on 2026-07-18 20:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyconfig'),
        ('labours', '0003_attendance'),
        ('sites', '0004_privatesitecash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='First record date after the previous session ended.')),
                ('end_date', models.DateField(help_text='Last sealed record date.')),
                ('created_date', models.DateField(default=django.utils.timezone.localdate)),
                ('present_days', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('salary_earnings', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('extra_earnings', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_payment', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_return', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='labours.labour')),
            ],
        ),
        migrations.CreateModel(
            name='LabourSessionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(max_length=255)),
                ('present_days', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('salary_earnings', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('extra_earnings', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_payment', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_return', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_details', models.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='labours.laboursession')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_session_details', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='laboursession',
            constraint=models.UniqueConstraint(fields=('created_date', 'labour'), name='uq_labour_session_created_date_labour'),
        ),
    ]
