# Generated by Django 5.1.15 on 2026-09-02 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0003_labour_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboursession',
            name='labour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='labours.labour'),
        ),
    ]
