# Generated by Django 5.1.15 on 2026-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0004_laboursession_laboursessiondetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='last_session_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
