# Generated by Django 5.1.15 on 2026-07-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0005_labour_last_session_date'),
        ('sites', '0004_privatesitecash'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboursession',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_sessions', to='sites.site'),
        ),
    ]
