# Generated by Django 5.1.15 on 2026-07-22 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0006_laboursession_site'),
        ('sites', '0004_privatesitecash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='current_site',
            field=models.ForeignKey(blank=True, help_text='One site at a time; reassign = move. NULL = unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labours', to='sites.site'),
        ),
    ]
