# Generated by Django 5.1.15 on 2026-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0007_labour_current_site_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboursession',
            name='site',
        ),
        migrations.AddField(
            model_name='laboursession',
            name='affected_attendance_rows',
            field=models.PositiveIntegerField(default=0, help_text='Attendance rows sealed into this session.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboursession',
            name='affected_payment_rows',
            field=models.PositiveIntegerField(default=0, help_text='Payment rows sealed into this session.'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LabourSessionDetail',
        ),
    ]
