# Generated by Django 5.1.15 on 2026-07-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0008_remove_laboursession_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboursession',
            name='previous_payable',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
