# Generated by Django 5.1.15 on 2026-07-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0009_laboursession_previous_payable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourpayment',
            name='category',
        ),
    ]
