# Generated by Django 5.1.15 on 2026-08-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0010_remove_labourpayment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labour',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='labourpayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='laboursession',
            name='created_by',
        ),
    ]
