# Generated by Django 5.1.15 on 2026-07-09 09:56

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import sites.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Basement, Floor-1.', max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_done', models.BooleanField(default=False, help_text='Mark as done => deactivates.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_categories', to='sites.site')),
            ],
            options={
                'verbose_name_plural': 'billing categories',
                'constraints': [models.UniqueConstraint(fields=('site', 'name'), name='uq_billingcategory_site_name')],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_record_create_window', models.IntegerField(default=1)),
                ('daily_record_update_window', models.IntegerField(default=1)),
                ('daily_record_delete_window', models.IntegerField(default=1)),
                ('attendance_per_labour_per_day_limit', models.IntegerField(default=1, help_text='-1 means no limit.', validators=[django.core.validators.MinValueValidator(-1)])),
                ('extra_per_labour_per_day_limit', models.IntegerField(default=1, help_text='-1 means no limit.', validators=[django.core.validators.MinValueValidator(-1)])),
                ('fooding_per_labour_per_day_limit', models.IntegerField(default=1, help_text='-1 means no limit.', validators=[django.core.validators.MinValueValidator(-1)])),
                ('advance_per_labour_per_day_limit', models.IntegerField(default=-1, help_text='-1 means no limit.', validators=[django.core.validators.MinValueValidator(-1)])),
                ('attendance_present_choices', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=3), default=sites.models.default_present_choices, help_text='Allowed present values per attendance row.', size=None)),
                ('salary_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_max', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(0)])),
                ('fooding_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fooding_max', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)])),
                ('advance_min', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('advance_max', models.IntegerField(default=100000, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='sites.site')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('salary_min__gte', 0), ('salary_max__gte', models.F('salary_min'))), name='chk_siteconfig_salary_range'), models.CheckConstraint(condition=models.Q(('fooding_min__gte', 0), ('fooding_max__gte', models.F('fooding_min'))), name='chk_siteconfig_fooding_range'), models.CheckConstraint(condition=models.Q(('advance_min__gte', 0), ('advance_max__gte', models.F('advance_min'))), name='chk_siteconfig_advance_range')],
            },
        ),
    ]
