# Generated by Django 5.1.15 on 2026-07-15 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyconfig'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Basement, Floor-1.', max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_done', models.BooleanField(default=False, help_text='Mark as done => deactivates.')),
            ],
            options={
                'verbose_name_plural': 'billing categories',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_site_company_name'),
        ),
        migrations.AddField(
            model_name='billingcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company'),
        ),
        migrations.AddField(
            model_name='billingcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingcategory',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_categories', to='sites.site'),
        ),
        migrations.AddConstraint(
            model_name='billingcategory',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='uq_billingcategory_site_name'),
        ),
    ]
