# Generated by Django 5.1.15 on 2026-07-12 04:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyconfig'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_record_create_window', models.IntegerField(default=1)),
                ('daily_record_update_window', models.IntegerField(default=1)),
                ('daily_record_delete_window', models.IntegerField(default=1)),
                ('attendance_limit_per_day', models.IntegerField(default=1, help_text='-1 means no limit.', validators=[django.core.validators.MinValueValidator(-1)])),
                ('extra_limit_per_day', models.IntegerField(default=1, help_text='-1 means no limit.', validators=[django.core.validators.MinValueValidator(-1)])),
                ('fooding_limit_per_day', models.IntegerField(default=1, help_text='-1 means no limit.', validators=[django.core.validators.MinValueValidator(-1)])),
                ('advance_limit_per_day', models.IntegerField(default=-1, help_text='-1 means no limit.', validators=[django.core.validators.MinValueValidator(-1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Basement, Floor-1.', max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_done', models.BooleanField(default=False, help_text='Mark as done => deactivates.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_categories', to='sites.site')),
            ],
            options={
                'verbose_name_plural': 'billing categories',
                'constraints': [models.UniqueConstraint(fields=('site', 'name'), name='uq_billingcategory_site_name')],
            },
        ),
    ]
