# Generated by Django 5.1.15 on 2026-07-17 10:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyconfig'),
        ('sites', '0002_billingcategory_site_is_closed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('cost', 'Cost')], max_length=16)),
                ('category', models.CharField(blank=True, choices=[('food', 'Food'), ('equipment', 'Equipment')], help_text='Typically used for cost (food | equipment); optional for deposit/withdrawal.', max_length=16, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('billing', models.ForeignKey(blank=True, help_text='Optional billing category; nullable for all types.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='sites.billingcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cash_entries', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
