# Generated by Django 5.1.15 on 2026-07-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_billingcategory_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
