# Generated by Django 5.1.15 on 2026-08-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_privatesitecash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='privatesitecash',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='site',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sitecash',
            name='created_by',
        ),
    ]
