# Generated by Django 5.1.15 on 2026-08-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_remove_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecash',
            name='category',
        ),
    ]
