# Generated by Django 5.1.15 on 2026-08-29 10:46

import sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0006_remove_sitecash_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecash",
            name="file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=sites.models.sitecash_file_upload_to,
            ),
        ),
    ]
