# Generated by Django 5.1.15 on 2026-09-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_remove_site_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesitecash',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_cash_entries', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='sitecash',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to='sites.site'),
        ),
    ]
